[run]
tests = true

[issues]
max-issues-per-linter = 0
max-same-issues = 0
new = false

[linters]
enable = ["contextcheck", "unparam"]

[linters-settings.errcheck]
# Don't allow setting of error to the blank identifier. If there is a legitimate
# reason, there should be a nolint with an explanation.
check-blank = true
