[run]
tests = true

[issues]
max-issues-per-linter = 0
max-same-issues = 0
new = false

[linters]
enable = [
    "contextcheck",
    "copyloopvar",
    "errcheck",
    "errname",
    "errorlint",
    "godot",
    "gofmt",
    "goimports",
    "govet",
    "ineffassign",
    "misspell",
    "nakedret",
    "nilerr",
    "nilnil",
    "predeclared",
    "reassign",
    #"revive", # Quite nitpicky, useful to run manually.
    "stylecheck",
    "staticcheck",
    "tagliatelle",
    "thelper",
    "tparallel",
    "unconvert",
    "unparam",
    "unused",
    "usestdlibvars",
    "usetesting",
    "wastedassign",
]

[linters-settings.errcheck]
# Don't allow setting of error to the blank identifier. If there is a legitimate
# reason, there should be a nolint with an explanation.
check-blank = true

[linters-settings.tagliatelle.case]
rules = { json = "snake" }
