---
version: "3"

volumes:
  postgres-data: {}

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: sparklemuffin
      POSTGRES_USER: sparklemuffin
      POSTGRES_PASSWORD: sparklemuffin
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U sparklemuffin -d sparklemuffin"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 15432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
