---
version: "3"

volumes:
  postgres-data: {}

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: yawbe
      POSTGRES_USER: yawbe
      POSTGRES_PASSWORD: yawbe
    ports:
      - 15432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
