---
name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: make build

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: jontze/action-mdbook@v3
        with:
          mdbook-version: "~0.4.36"
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Generate documentation
        run: make docs

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: "v1.58"

      - name: Vulnerabilities
        id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-file: go.mod
          repo-checkout: false

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test
        run: make cover
