---
name: Docs

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: jontze/action-mdbook@v3
        with:
          mdbook-version: "~0.4.43"
          use-linkcheck: true
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Show mdbook version
        run: mdbook --version

      - name: Show linkcheck version
        run: mdbook-linkcheck --version

      - name: Generate documentation
        run: make docs

      - name: Upload documentation as an artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs/book"

  publish:
    if: github.ref == 'refs/heads/main'
    needs: generate

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
